version: "3.8"

services:
  db:
    image: postgres
    restart: always
    container_name: db-votes
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: votes
    ports:
      - "5432:5432"
