

import './global.css';
import NavBar from '../components/ui/NavBar/NavBar';
import { ThemeProvider } from '../components/theme-provider';

export const metadata = {
  title: 'Welcome to client',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute={'class'}
          defaultTheme={'system'}
          enableColorScheme
          disableTransitionOnChange
        >
          <NavBar />
          <main>
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
